name: 'Release'
on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: ".github/changelog_configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: ${{ steps.get_tag_name.outputs.TAG_NAME }}
      - uses: UziTech/action-setup-atom@v2
      - name: Publish package
        run: apm publish -t ${{ steps.get_tag_name.outputs.TAG_NAME }}
        env:
          ATOM_ACCESS_TOKEN: ${{ secrets.ATOM_ACCESS_TOKEN }}
